name: Publish Docker Image
on:
  workflow_run:
    workflows: [ Check ]
    types: [ completed ]
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  publish-oci-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use cachix binary cache
        uses: cachix/cachix-action@v12
        with:
          name: source-fox
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - id: sanitize-repository-name
        shell: pwsh
        run: |
          "::set-output name=repository::$($env:GITHUB_REPOSITORY.ToLowerInvariant())"
      - name: Build and load Docker image
        run: |
          nix build .#server-docker-stream && ./result | docker load
          docker tag source-warden:latest ${{ env.REGISTRY }}/${{ steps.sanitize-repository-name.outputs.repository }}:latest
      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ steps.sanitize-repository-name.outputs.repository }}:latest